-- 코드를 입력하세요
SELECT DISTINCT USER_ID, PRODUCT_ID FROM (
SELECT USER_ID, PRODUCT_ID, COUNT(*) OVER(PARTITION BY USER_ID, PRODUCT_ID) CNT
FROM ONLINE_SALE
ORDER BY CNT DESC
)
WHERE CNT > 1
ORDER BY 1, 2 DESC;